// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PageDocumentDataSlicesSlice =
    | FaqSlice
    | YogaArambhaSlice
    | OurYogaStorySlice
    | EventHighlightsGallerySlice
    | UpcomingWorkshopSlice
    | RightContentLeftSliderVerticalSlice
    | GroupClassSlice
    | VideoTestimonialsSlice
    | LeftContentRightImageSlice
    | LeftImageRighContentSlice
    | LeftContentRightSliderVerticalSlice
    | RecognitionSlice
    | SlicesSlice
    | HeroSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.TitleField

    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
     * Meta Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

export type AllDocumentTypes = PageDocument

/**
 * Item in *EventHighlightsGallery → Default → Primary → Albums*
 */
export interface EventHighlightsGallerySliceDefaultPrimaryAlbumsItem {
    /**
     * image field in *EventHighlightsGallery → Default → Primary → Albums*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.albums[].image
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    image: prismic.LinkToMediaField

    /**
     * Album Name field in *EventHighlightsGallery → Default → Primary → Albums*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.albums[].album_name
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    album_name: prismic.KeyTextField
}

/**
 * Primary content in *EventHighlightsGallery → Default → Primary*
 */
export interface EventHighlightsGallerySliceDefaultPrimary {
    /**
     * Section Title field in *EventHighlightsGallery → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.section_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    section_title: prismic.KeyTextField

    /**
     * Albums field in *EventHighlightsGallery → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.albums[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    albums: prismic.GroupField<
        Simplify<EventHighlightsGallerySliceDefaultPrimaryAlbumsItem>
    >

    /**
     * Button Text field in *EventHighlightsGallery → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *EventHighlightsGallery → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: event_highlights_gallery.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField
}

/**
 * Default variation for EventHighlightsGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventHighlightsGallerySliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<EventHighlightsGallerySliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *EventHighlightsGallery*
 */
type EventHighlightsGallerySliceVariation = EventHighlightsGallerySliceDefault

/**
 * EventHighlightsGallery Shared Slice
 *
 * - **API ID**: `event_highlights_gallery`
 * - **Description**: EventHighlightsGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventHighlightsGallerySlice = prismic.SharedSlice<
    'event_highlights_gallery',
    EventHighlightsGallerySliceVariation
>

/**
 * Item in *Faq → Default → Primary → Faqs*
 */
export interface FaqSliceDefaultPrimaryFaqsItem {
    /**
     * Question field in *Faq → Default → Primary → Faqs*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.faqs[].question
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    question: prismic.KeyTextField

    /**
     * answer field in *Faq → Default → Primary → Faqs*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.faqs[].answer
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    answer: prismic.KeyTextField
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
    /**
     * Title field in *Faq → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Faqs field in *Faq → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.faqs[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    faqs: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryFaqsItem>>

    /**
     * Bottom Text field in *Faq → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.bottom_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    bottom_text: prismic.KeyTextField

    /**
     * Button Text field in *Faq → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *Faq → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<FaqSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<'faq', FaqSliceVariation>

/**
 * Primary content in *GroupClass → Default → Primary*
 */
export interface GroupClassSliceDefaultPrimary {
    /**
     * Title field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Title Coloured field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.title_coloured
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title_coloured: prismic.KeyTextField

    /**
     * Title Coloured Color field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.title_coloured_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    title_coloured_color: prismic.ColorField

    /**
     * Description field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField

    /**
     * Button Text field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Image field in *GroupClass → Default → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: group_class.default.primary.image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>
}

/**
 * Default variation for GroupClass Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GroupClassSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<GroupClassSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *GroupClass*
 */
type GroupClassSliceVariation = GroupClassSliceDefault

/**
 * GroupClass Shared Slice
 *
 * - **API ID**: `group_class`
 * - **Description**: GroupClass
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GroupClassSlice = prismic.SharedSlice<
    'group_class',
    GroupClassSliceVariation
>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Subtitle field in *Hero → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.default.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField

    /**
     * Button Text field in *Hero → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *Hero → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Video Background Link field in *Hero → Default → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.default.primary.video_background_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    video_background_link: prismic.LinkToMediaField
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HeroSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *LeftContentRightImage → Default → Primary*
 */
export interface LeftContentRightImageSliceDefaultPrimary {
    /**
     * Title field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Title Coloured field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.title_coloured
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title_coloured: prismic.KeyTextField

    /**
     * Title Coloured Color field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.title_coloured_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    title_coloured_color: prismic.ColorField

    /**
     * Description field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField

    /**
     * Button Text field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Right Image field in *LeftContentRightImage → Default → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_image.default.primary.right_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    right_image: prismic.ImageField<never>
}

/**
 * Default variation for LeftContentRightImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftContentRightImageSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<LeftContentRightImageSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *LeftContentRightImage*
 */
type LeftContentRightImageSliceVariation = LeftContentRightImageSliceDefault

/**
 * LeftContentRightImage Shared Slice
 *
 * - **API ID**: `left_content_right_image`
 * - **Description**: LeftContentRightImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftContentRightImageSlice = prismic.SharedSlice<
    'left_content_right_image',
    LeftContentRightImageSliceVariation
>

/**
 * Item in *LeftContentRightSliderVertical → Default → Primary → Content*
 */
export interface LeftContentRightSliderVerticalSliceDefaultPrimaryContentItem {
    /**
     * Content Title field in *LeftContentRightSliderVertical → Default → Primary → Content*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_slider_vertical.default.primary.content[].content_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    content_title: prismic.KeyTextField

    /**
     * Content Description field in *LeftContentRightSliderVertical → Default → Primary → Content*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_slider_vertical.default.primary.content[].content_description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    content_description: prismic.KeyTextField

    /**
     * Slider Image field in *LeftContentRightSliderVertical → Default → Primary → Content*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_slider_vertical.default.primary.content[].slider_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    slider_image: prismic.ImageField<never>
}

/**
 * Primary content in *LeftContentRightSliderVertical → Default → Primary*
 */
export interface LeftContentRightSliderVerticalSliceDefaultPrimary {
    /**
     * Title field in *LeftContentRightSliderVertical → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_slider_vertical.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *LeftContentRightSliderVertical → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: left_content_right_slider_vertical.default.primary.content[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    content: prismic.GroupField<
        Simplify<LeftContentRightSliderVerticalSliceDefaultPrimaryContentItem>
    >
}

/**
 * Default variation for LeftContentRightSliderVertical Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftContentRightSliderVerticalSliceDefault =
    prismic.SharedSliceVariation<
        'default',
        Simplify<LeftContentRightSliderVerticalSliceDefaultPrimary>,
        never
    >

/**
 * Slice variation for *LeftContentRightSliderVertical*
 */
type LeftContentRightSliderVerticalSliceVariation =
    LeftContentRightSliderVerticalSliceDefault

/**
 * LeftContentRightSliderVertical Shared Slice
 *
 * - **API ID**: `left_content_right_slider_vertical`
 * - **Description**: LeftContentRightSliderVertical
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftContentRightSliderVerticalSlice = prismic.SharedSlice<
    'left_content_right_slider_vertical',
    LeftContentRightSliderVerticalSliceVariation
>

/**
 * Primary content in *LeftImageRighContent → Default → Primary*
 */
export interface LeftImageRighContentSliceDefaultPrimary {
    /**
     * LeftImage field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.leftimage
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    leftimage: prismic.ImageField<never>

    /**
     * Title field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Title Coloured field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.title_coloured
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title_coloured: prismic.KeyTextField

    /**
     * Description field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField

    /**
     * Button Text field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *LeftImageRighContent → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: left_image_righ_content.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField
}

/**
 * Default variation for LeftImageRighContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftImageRighContentSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<LeftImageRighContentSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *LeftImageRighContent*
 */
type LeftImageRighContentSliceVariation = LeftImageRighContentSliceDefault

/**
 * LeftImageRighContent Shared Slice
 *
 * - **API ID**: `left_image_righ_content`
 * - **Description**: LeftImageRighContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftImageRighContentSlice = prismic.SharedSlice<
    'left_image_righ_content',
    LeftImageRighContentSliceVariation
>

/**
 * Item in *OurYogaStory → Default → Primary → Content*
 */
export interface OurYogaStorySliceDefaultPrimaryContentItem {
    /**
     * Content Description field in *OurYogaStory → Default → Primary → Content*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.content[].content_description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content_description: prismic.RichTextField

    /**
     * Content Image field in *OurYogaStory → Default → Primary → Content*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.content[].content_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    content_image: prismic.ImageField<never>
}

/**
 * Primary content in *OurYogaStory → Default → Primary*
 */
export interface OurYogaStorySliceDefaultPrimary {
    /**
     * Title field in *OurYogaStory → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField

    /**
     * Button Text field in *OurYogaStory → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *OurYogaStory → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Content field in *OurYogaStory → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: our_yoga_story.default.primary.content[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    content: prismic.GroupField<
        Simplify<OurYogaStorySliceDefaultPrimaryContentItem>
    >
}

/**
 * Default variation for OurYogaStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurYogaStorySliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<OurYogaStorySliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *OurYogaStory*
 */
type OurYogaStorySliceVariation = OurYogaStorySliceDefault

/**
 * OurYogaStory Shared Slice
 *
 * - **API ID**: `our_yoga_story`
 * - **Description**: OurYogaStory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurYogaStorySlice = prismic.SharedSlice<
    'our_yoga_story',
    OurYogaStorySliceVariation
>

/**
 * Item in *Recognition → Default → Primary → Logos*
 */
export interface RecognitionSliceDefaultPrimaryLogosItem {
    /**
     * logo field in *Recognition → Default → Primary → Logos*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: recognition.default.primary.logos[].logo
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logo: prismic.ImageField<never>
}

/**
 * Primary content in *Recognition → Default → Primary*
 */
export interface RecognitionSliceDefaultPrimary {
    /**
     * Description field in *Recognition → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: recognition.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField

    /**
     * Logos field in *Recognition → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: recognition.default.primary.logos[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    logos: prismic.GroupField<Simplify<RecognitionSliceDefaultPrimaryLogosItem>>
}

/**
 * Default variation for Recognition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecognitionSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<RecognitionSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *Recognition*
 */
type RecognitionSliceVariation = RecognitionSliceDefault

/**
 * Recognition Shared Slice
 *
 * - **API ID**: `recognition`
 * - **Description**: Recognition
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecognitionSlice = prismic.SharedSlice<
    'recognition',
    RecognitionSliceVariation
>

/**
 * Item in *RightContentLeftSliderVertical → Default → Primary → Slider Images*
 */
export interface RightContentLeftSliderVerticalSliceDefaultPrimarySliderImagesItem {
    /**
     * image field in *RightContentLeftSliderVertical → Default → Primary → Slider Images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.slider_images[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>
}

/**
 * Primary content in *RightContentLeftSliderVertical → Default → Primary*
 */
export interface RightContentLeftSliderVerticalSliceDefaultPrimary {
    /**
     * Title field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Description field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField

    /**
     * Subtitle field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    subtitle: prismic.RichTextField

    /**
     * Button Text field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Slider Images field in *RightContentLeftSliderVertical → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: right_content_left_slider_vertical.default.primary.slider_images[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    slider_images: prismic.GroupField<
        Simplify<RightContentLeftSliderVerticalSliceDefaultPrimarySliderImagesItem>
    >
}

/**
 * Default variation for RightContentLeftSliderVertical Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RightContentLeftSliderVerticalSliceDefault =
    prismic.SharedSliceVariation<
        'default',
        Simplify<RightContentLeftSliderVerticalSliceDefaultPrimary>,
        never
    >

/**
 * Slice variation for *RightContentLeftSliderVertical*
 */
type RightContentLeftSliderVerticalSliceVariation =
    RightContentLeftSliderVerticalSliceDefault

/**
 * RightContentLeftSliderVertical Shared Slice
 *
 * - **API ID**: `right_content_left_slider_vertical`
 * - **Description**: RightContentLeftSliderVertical
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RightContentLeftSliderVerticalSlice = prismic.SharedSlice<
    'right_content_left_slider_vertical',
    RightContentLeftSliderVerticalSliceVariation
>

/**
 * Item in *Stats → Default → Primary → StatsCollection*
 */
export interface SlicesSliceDefaultPrimaryStatscollectionItem {
    /**
     * icon field in *Stats → Default → Primary → StatsCollection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: slices.default.primary.statscollection[].icon
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    icon: prismic.ImageField<never>

    /**
     * label field in *Stats → Default → Primary → StatsCollection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: slices.default.primary.statscollection[].label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    label: prismic.KeyTextField

    /**
     * count field in *Stats → Default → Primary → StatsCollection*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: slices.default.primary.statscollection[].count
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    count: prismic.NumberField
}

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface SlicesSliceDefaultPrimary {
    /**
     * StatsCollection field in *Stats → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: slices.default.primary.statscollection[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    statscollection: prismic.GroupField<
        Simplify<SlicesSliceDefaultPrimaryStatscollectionItem>
    >
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlicesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SlicesSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *Stats*
 */
type SlicesSliceVariation = SlicesSliceDefault

/**
 * Stats Shared Slice
 *
 * - **API ID**: `slices`
 * - **Description**: Slices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlicesSlice = prismic.SharedSlice<'slices', SlicesSliceVariation>

/**
 * Item in *WorkshopRow → Default → Primary → Row*
 */
export interface UpcomingWorkshopSliceDefaultPrimaryRowItem {
    /**
     * Month field in *WorkshopRow → Default → Primary → Row*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.row[].month
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    month: prismic.KeyTextField

    /**
     * Teacher field in *WorkshopRow → Default → Primary → Row*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.row[].teacher
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    teacher: prismic.KeyTextField

    /**
     * Date Time field in *WorkshopRow → Default → Primary → Row*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.row[].date_time
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    date_time: prismic.TimestampField

    /**
     * Topic field in *WorkshopRow → Default → Primary → Row*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.row[].topic
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    topic: prismic.KeyTextField
}

/**
 * Primary content in *WorkshopRow → Default → Primary*
 */
export interface UpcomingWorkshopSliceDefaultPrimary {
    /**
     * Title field in *WorkshopRow → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Row field in *WorkshopRow → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.row[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    row: prismic.GroupField<
        Simplify<UpcomingWorkshopSliceDefaultPrimaryRowItem>
    >

    /**
     * Button Text field in *WorkshopRow → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *WorkshopRow → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: upcoming_workshop.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField
}

/**
 * Default variation for WorkshopRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UpcomingWorkshopSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<UpcomingWorkshopSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *WorkshopRow*
 */
type UpcomingWorkshopSliceVariation = UpcomingWorkshopSliceDefault

/**
 * WorkshopRow Shared Slice
 *
 * - **API ID**: `upcoming_workshop`
 * - **Description**: UpcomingWorkshop
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UpcomingWorkshopSlice = prismic.SharedSlice<
    'upcoming_workshop',
    UpcomingWorkshopSliceVariation
>

/**
 * Item in *VideoTestimonials → Default → Primary → Video Links*
 */
export interface VideoTestimonialsSliceDefaultPrimaryVideoLinksItem {
    /**
     * Youtube Embed ID field in *VideoTestimonials → Default → Primary → Video Links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_testimonials.default.primary.video_links[].youtube_embed_id
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    youtube_embed_id: prismic.KeyTextField
}

/**
 * Primary content in *VideoTestimonials → Default → Primary*
 */
export interface VideoTestimonialsSliceDefaultPrimary {
    /**
     * Title field in *VideoTestimonials → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_testimonials.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Subtitle field in *VideoTestimonials → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_testimonials.default.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField

    /**
     * Video Links field in *VideoTestimonials → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: video_testimonials.default.primary.video_links[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    video_links: prismic.GroupField<
        Simplify<VideoTestimonialsSliceDefaultPrimaryVideoLinksItem>
    >
}

/**
 * Default variation for VideoTestimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoTestimonialsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<VideoTestimonialsSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *VideoTestimonials*
 */
type VideoTestimonialsSliceVariation = VideoTestimonialsSliceDefault

/**
 * VideoTestimonials Shared Slice
 *
 * - **API ID**: `video_testimonials`
 * - **Description**: VideoTestimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoTestimonialsSlice = prismic.SharedSlice<
    'video_testimonials',
    VideoTestimonialsSliceVariation
>

/**
 * Primary content in *YogaArambha → Default → Primary*
 */
export interface YogaArambhaSliceDefaultPrimary {
    /**
     * Title field in *YogaArambha → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: yoga_arambha.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Description field in *YogaArambha → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: yoga_arambha.default.primary.description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField

    /**
     * Button Text field in *YogaArambha → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: yoga_arambha.default.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField

    /**
     * Button Link field in *YogaArambha → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: yoga_arambha.default.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField

    /**
     * Youtube Embed ID field in *YogaArambha → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: yoga_arambha.default.primary.youtube_embed_id
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    youtube_embed_id: prismic.KeyTextField
}

/**
 * Default variation for YogaArambha Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YogaArambhaSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<YogaArambhaSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *YogaArambha*
 */
type YogaArambhaSliceVariation = YogaArambhaSliceDefault

/**
 * YogaArambha Shared Slice
 *
 * - **API ID**: `yoga_arambha`
 * - **Description**: YogaArambha
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YogaArambhaSlice = prismic.SharedSlice<
    'yoga_arambha',
    YogaArambhaSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>
    }

    interface CreateWriteClient {
        (
            repositoryNameOrEndpoint: string,
            options: prismic.WriteClientConfig
        ): prismic.WriteClient<AllDocumentTypes>
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>
    }

    namespace Content {
        export type {
            PageDocument,
            PageDocumentData,
            PageDocumentDataSlicesSlice,
            AllDocumentTypes,
            EventHighlightsGallerySlice,
            EventHighlightsGallerySliceDefaultPrimaryAlbumsItem,
            EventHighlightsGallerySliceDefaultPrimary,
            EventHighlightsGallerySliceVariation,
            EventHighlightsGallerySliceDefault,
            FaqSlice,
            FaqSliceDefaultPrimaryFaqsItem,
            FaqSliceDefaultPrimary,
            FaqSliceVariation,
            FaqSliceDefault,
            GroupClassSlice,
            GroupClassSliceDefaultPrimary,
            GroupClassSliceVariation,
            GroupClassSliceDefault,
            HeroSlice,
            HeroSliceDefaultPrimary,
            HeroSliceVariation,
            HeroSliceDefault,
            LeftContentRightImageSlice,
            LeftContentRightImageSliceDefaultPrimary,
            LeftContentRightImageSliceVariation,
            LeftContentRightImageSliceDefault,
            LeftContentRightSliderVerticalSlice,
            LeftContentRightSliderVerticalSliceDefaultPrimaryContentItem,
            LeftContentRightSliderVerticalSliceDefaultPrimary,
            LeftContentRightSliderVerticalSliceVariation,
            LeftContentRightSliderVerticalSliceDefault,
            LeftImageRighContentSlice,
            LeftImageRighContentSliceDefaultPrimary,
            LeftImageRighContentSliceVariation,
            LeftImageRighContentSliceDefault,
            OurYogaStorySlice,
            OurYogaStorySliceDefaultPrimaryContentItem,
            OurYogaStorySliceDefaultPrimary,
            OurYogaStorySliceVariation,
            OurYogaStorySliceDefault,
            RecognitionSlice,
            RecognitionSliceDefaultPrimaryLogosItem,
            RecognitionSliceDefaultPrimary,
            RecognitionSliceVariation,
            RecognitionSliceDefault,
            RightContentLeftSliderVerticalSlice,
            RightContentLeftSliderVerticalSliceDefaultPrimarySliderImagesItem,
            RightContentLeftSliderVerticalSliceDefaultPrimary,
            RightContentLeftSliderVerticalSliceVariation,
            RightContentLeftSliderVerticalSliceDefault,
            SlicesSlice,
            SlicesSliceDefaultPrimaryStatscollectionItem,
            SlicesSliceDefaultPrimary,
            SlicesSliceVariation,
            SlicesSliceDefault,
            UpcomingWorkshopSlice,
            UpcomingWorkshopSliceDefaultPrimaryRowItem,
            UpcomingWorkshopSliceDefaultPrimary,
            UpcomingWorkshopSliceVariation,
            UpcomingWorkshopSliceDefault,
            VideoTestimonialsSlice,
            VideoTestimonialsSliceDefaultPrimaryVideoLinksItem,
            VideoTestimonialsSliceDefaultPrimary,
            VideoTestimonialsSliceVariation,
            VideoTestimonialsSliceDefault,
            YogaArambhaSlice,
            YogaArambhaSliceDefaultPrimary,
            YogaArambhaSliceVariation,
            YogaArambhaSliceDefault,
        }
    }
}
