// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
    causes_of_pcos: dynamic(() => import('./CausesOfPcos')),
    enroll_section: dynamic(() => import('./EnrollSection')),
    event_highlights_gallery: dynamic(() => import('./EventHighlightsGallery')),
    faq: dynamic(() => import('./Faq')),
    group_class: dynamic(() => import('./GroupClass')),
    hero: dynamic(() => import('./Hero')),
    how_yoga_helps: dynamic(() => import('./HowYogaHelps')),
    left_content_right_image: dynamic(() => import('./LeftContentRightImage')),
    left_content_right_slider_vertical: dynamic(
        () => import('./LeftContentRightSliderVertical')
    ),
    left_image_righ_content: dynamic(() => import('./LeftImageRighContent')),
    our_yoga_story: dynamic(() => import('./OurYogaStory')),
    pcos_hero: dynamic(() => import('./PcosHero')),
    recognition: dynamic(() => import('./Recognition')),
    right_content_left_slider_vertical: dynamic(
        () => import('./RightContentLeftSliderVertical')
    ),
    slices: dynamic(() => import('./Stats')),
    symptoms: dynamic(() => import('./Symptoms')),
    upcoming_workshop: dynamic(() => import('./WorkshopRow')),
    video_testimonials: dynamic(() => import('./VideoTestimonials')),
    why_join: dynamic(() => import('./WhyJoin')),
    yoga_arambha: dynamic(() => import('./YogaArambha')),
    yoga_practices: dynamic(() => import('./YogaPractices')),
}
