// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
    advantages_of_personal_training: dynamic(
        () => import('./AdvantagesOfPersonalTraining')
    ),
    causes_of_pcos: dynamic(() => import('./CausesOfPcos')),
    class_format: dynamic(() => import('./ClassFormat')),
    class_intensity_table: dynamic(() => import('./ClassIntensityTable')),
    consider_personal_training: dynamic(
        () => import('./ConsiderPersonalTraining')
    ),
    enroll_section: dynamic(() => import('./EnrollSection')),
    event_highlights_gallery: dynamic(() => import('./EventHighlightsGallery')),
    faq: dynamic(() => import('./Faq')),
    group_class: dynamic(() => import('./GroupClass')),
    group_class_format: dynamic(() => import('./GroupClassFormat')),
    group_class_hero: dynamic(() => import('./GroupClassHero')),
    group_class_pricing: dynamic(() => import('./GroupClassPricing')),
    group_information: dynamic(() => import('./GroupInformation')),
    hero: dynamic(() => import('./Hero')),
    how_yoga_helps: dynamic(() => import('./HowYogaHelps')),
    left_content_right_image: dynamic(() => import('./LeftContentRightImage')),
    left_content_right_slider_vertical: dynamic(
        () => import('./LeftContentRightSliderVertical')
    ),
    left_image_righ_content: dynamic(() => import('./LeftImageRighContent')),
    our_yoga_story: dynamic(() => import('./OurYogaStory')),
    pcos_hero: dynamic(() => import('./PcosHero')),
    personal_content: dynamic(() => import('./PersonalContent')),
    personal_session_hero: dynamic(() => import('./PersonalSessionHero')),
    personal_session_pricing: dynamic(() => import('./PersonalSessionPricing')),
    pros_and_cons: dynamic(() => import('./ProsAndCons')),
    recognition: dynamic(() => import('./Recognition')),
    right_content_left_slider_vertical: dynamic(
        () => import('./RightContentLeftSliderVertical')
    ),
    slices: dynamic(() => import('./Stats')),
    symptoms: dynamic(() => import('./Symptoms')),
    upcoming_workshop: dynamic(() => import('./WorkshopRow')),
    video_testimonials: dynamic(() => import('./VideoTestimonials')),
    why_join: dynamic(() => import('./WhyJoin')),
    yoga_arambha: dynamic(() => import('./YogaArambha')),
    yoga_practices: dynamic(() => import('./YogaPractices')),
}
